version: '3.8'

networks:
  default:
    driver: bridge

services:
  api:
    build: .
    networks:
      - default
    volumes:
      - .:/app  # Synchroniser tout le projet
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    command: ["/wait-for-it.sh", "db:5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dash:
    build:
      context: .
      dockerfile: dash_app/Dockerfile
    networks:
      - default
    volumes:
      - ./dash_app:/app
    ports:
      - "8050:8050"
    env_file:
      - .env
    depends_on:
      - api
    command: ["python", "app.py"]

volumes:
  postgres_data:
